# p-api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: p-api-service
spec:
  type: NodePort # Expõe a API para fora do cluster
  selector:
    app: p-api # Conecta este serviço ao Deployment acima
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000