# server-b-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-b
  template:
    metadata:
      labels:
        app: server-b
    spec:
      containers:
      - name: server-b-container
        image: car_build-server-b:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50052